---
abstract: 'Provides Moose interface for stash'
author:
  - 'Roman F. <romanf@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Runtime: 5.80
  Catalyst::Test: 0
  Test::More: 0
  lib::abs: 0
  namespace::autoclean: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Moostash
requires:
  MRO::Compat: 0
  Module::Load: 0
  Moose: 0
  strict: 0
  version: 0.77
  warnings: 0
resources:
  repository: git://github.com/moltar/Catalyst-Plugin-Moostash.git
version: v0.1.2
